// Per-brand config: theme CSS vars, fonts, logo, copy, and the REAL automotive film catalogs
// (from each brand's site + technical data sheets, researched 2026-07).
// Shade fields: sku = marketed shade number (chip label), vlt = actual measured VLT (used for
// tint-law checks — e.g. Autobahn "50" measures 47% VLT per its TDS), tser/ir/uv = spec-sheet %.

window.BRANDS = {
  // ── HÜPER OPTIK — huperoptikusa.com: white, signature lime green, German premium minimalism
  huper: {
    name: "Hüper Optik",
    logoImg: "assets/huper-logo-dark.png",
    favicon: "assets/huper-favicon.png",
    pageTitle: "Automotive Film Viewer",
    fontLinks: ["https://fonts.googleapis.com/css2?family=Abel&family=Open+Sans:wght@400;500;600&display=swap"],
    theme: {
      "--accent": "#81bd41", "--accent-text": "#ffffff",
      "--header-bg": "#ffffff", "--header-text": "#666666", "--logo-color": "#444444",
      "--page-bg": "#f9f9f9", "--panel-bg": "#ffffff", "--panel-text": "#555555",
      "--muted": "#999999", "--line": "#e4e4e0",
      "--heading-font": "'Abel','Arial Narrow',sans-serif", "--body-font": "'Open Sans',Arial,sans-serif",
      "--radius": "10px", "--chip-radius": "7px", "--btn-radius": "7px", "--nav-transform": "none",
      "--hero-bg": "#ffffff", "--hero-text": "#333333", "--hero-sub": "#666666",
    },
    hero: {
      eyebrow: "German-Engineered Nano-Ceramic",
      title: "Comfort Without Compromise",
      sub: "See every Hüper Optik shade on your vehicle — the world's first patented nano-ceramic film, installed by an authorized dealer near you.",
    },
    defaultPaint: "#e8eaec",
    defaultShade: { seriesIdx: 0, vlt: 30, sku: 30 },
    // the brand site's own dealer-locator page (hosts the iframed z-tark locator)
    dealerUrl: "https://www.huperoptikusa.com/store-locator-view/", dealerCta: "Find a Dealer Near You",
    ctaTagline: "Find a Hüper Optik dealer near you to request a quote.",
    products: [
      { name: "Ceramic Series", tech: "Titanium Nitride Nanoceramic",
        tagline: "The world's first patented nano-ceramic film — dual-layer Titanium Nitride. No metals, no dyes, will not fade or corrode.",
        warranty: "Lifetime warranty, including color.",
        shades: [
          { sku: 5,  vlt: 6,  tser: 75, ir: 92, uv: 99 },
          { sku: 15, vlt: 15, tser: 73, ir: 96, uv: 99 },
          { sku: 20, vlt: 21, tser: 68, ir: 91, uv: 99 },
          { sku: 30, vlt: 30, tser: 63, ir: 86, uv: 99 },
          { sku: 35, vlt: 34, tser: 61, ir: 81, uv: 99 },
          { sku: 40, vlt: 42, tser: 55, ir: 80, uv: 99 },
          { sku: 45, vlt: 44, tser: 54, ir: 76, uv: 99 },
          { sku: 50, vlt: 50, tser: 50, ir: 68, uv: 99 },
          { sku: 60, vlt: 60, tser: 43, ir: 60, uv: 99 },
          { sku: 70, vlt: 71, tser: 48, ir: 88, uv: 99 },
        ] },
      { name: "Fusion Series", tech: "Dual-Reflective Hybrid",
        tagline: "A fusion of performance, aesthetics, and neutral tones — with low interior reflectivity for better visibility out at night.",
        warranty: "Limited lifetime warranty.",
        shades: [
          { sku: 10, vlt: 11, tser: 77, ir: null, uv: 99 },
          { sku: 20, vlt: 20, tser: 69, ir: null, uv: 99 },
          { sku: 28, vlt: 27, tser: 65, ir: null, uv: 99 },
          { sku: 40, vlt: 41, tser: 47, ir: null, uv: 99 },
        ] },
      { name: "Xtreme Optiks", tech: "Dye-Stable Film",
        tagline: "Sophisticated style with a budget in mind — dye-stable film guaranteed not to fade or change color.",
        warranty: "Limited lifetime warranty.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 40, ir: null, uv: 99 },
          { sku: 20, vlt: 20, tser: 34, ir: null, uv: 99 },
          { sku: 35, vlt: 32, tser: 34, ir: null, uv: 99 },
          { sku: 40, vlt: 43, tser: 30, ir: null, uv: 99 },
          { sku: 55, vlt: 59, tser: 26, ir: null, uv: 99 },
        ] },
      { name: "Klar 85", tech: "Near-Invisible Ceramic",
        tagline: "Nearly invisible ceramic heat rejection — the windshield and no-privacy solution.",
        warranty: "Limited lifetime warranty.",
        shades: [
          { sku: 85, vlt: 85, tser: 32, ir: 42, uv: 99 },
        ] },
    ],
  },

  // ── AUTOBAHN — autobahnwindowfilms.com: black heroes, crimson square CTAs, "NO LIMITS"
  autobahn: {
    name: "Autobahn",
    logoImg: null, // site has no clean wordmark image; white lowercase text matches the brand
    logoText: "autobahn™",
    pageTitle: "Film Simulator",
    fontLinks: ["https://fonts.googleapis.com/css2?family=Orbitron:wght@600;800&family=Cairo:wght@600;700&family=Open+Sans:wght@400;500;600&display=swap"],
    theme: {
      "--accent": "#9b000e", "--accent-text": "#ffffff",
      "--header-bg": "#262626", "--header-text": "#ffffff", "--logo-color": "#ffffff",
      "--page-bg": "#000000", "--panel-bg": "#151515", "--panel-text": "#e8e8e8",
      "--muted": "#8f8f8f", "--line": "#333333",
      "--heading-font": "'Cairo',sans-serif", "--display-font": "'Orbitron','Cairo',sans-serif",
      "--body-font": "'Open Sans',Arial,sans-serif",
      "--radius": "6px", "--chip-radius": "0px", "--btn-radius": "0px", "--nav-transform": "uppercase",
      "--stage-day": "radial-gradient(ellipse 120% 90% at 50% 18%, #26282b 0%, #121314 55%, #050506 100%)",
      "--stage-night": "radial-gradient(ellipse 120% 90% at 50% 18%, #16191f 0%, #0a0c10 55%, #030405 100%)",
      "--hero-bg": "#000000", "--hero-text": "#ffffff", "--hero-sub": "#9a9a9a", "--eyebrow": "#d20511",
      "--card-shadow": "none", "--card-border": "#2c2c2c",
    },
    hero: {
      eyebrow: "Since 2011 · Quality Guaranteed",
      title: "No Limits",
      sub: "Preview every Autobahn film on your vehicle. Pick your shade. Own the road.",
    },
    defaultPaint: "#1a1c1f",
    defaultShade: { seriesIdx: 1, vlt: 15, sku: 15 },
    // the brand site's own dealer-locator page (hosts the iframed z-tark locator)
    dealerUrl: "https://autobahnwindowfilms.com/dealer-locator/", dealerCta: "Find a Dealer Near You",
    ctaTagline: "Find an Autobahn dealer near you to request a quote.",
    products: [
      { name: "Ceramic i3+", tech: "4-Layer Nano-Ceramic · 99% IRR",
        tagline: "Nano-ceramic technology with no limits — the flagship, with 99% infrared rejection.",
        warranty: "Lifetime warranty — no hidden fees or deductibles.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 74, ir: 99, uv: 99 },
          { sku: 15, vlt: 15, tser: 70, ir: 99, uv: 99 },
          { sku: 30, vlt: 32, tser: 64, ir: 99, uv: 99 },
          { sku: 40, vlt: 42, tser: 62, ir: 99, uv: 99 },
        ] },
      { name: "Ceramic i3", tech: "3-Layer Nano-Ceramic · 93% IRR",
        tagline: "Superior performance — multi-layer nano-ceramic in seven shades.",
        warranty: "Lifetime warranty — no hidden fees or deductibles.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 71, ir: 93, uv: 99 },
          { sku: 15, vlt: 15, tser: 68, ir: 93, uv: 99 },
          { sku: 22, vlt: 22, tser: 66, ir: 93, uv: 99 },
          { sku: 33, vlt: 33, tser: 62, ir: 93, uv: 99 },
          { sku: 40, vlt: 40, tser: 60, ir: 93, uv: 99 },
          { sku: 56, vlt: 56, tser: 56, ir: 93, uv: 99 },
          { sku: 70, vlt: 67, tser: 50, ir: 93, uv: 99 },
        ] },
      { name: "Black Ceramic", tech: "Single-Layer Ceramic · 60% IRR",
        tagline: "Proven performance — premium single-layer ceramic.",
        warranty: "Lifetime warranty — no hidden fees or deductibles.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 63, ir: 60, uv: 99 },
          { sku: 15, vlt: 16, tser: 59, ir: 60, uv: 99 },
          { sku: 20, vlt: 21, tser: 56, ir: 60, uv: 99 },
          { sku: 30, vlt: 31, tser: 55, ir: 60, uv: 99 },
          { sku: 40, vlt: 40, tser: 53, ir: 60, uv: 99 },
          { sku: 50, vlt: 47, tser: 50, ir: 60, uv: 99 },
          { sku: 56, vlt: 54, tser: 49, ir: 60, uv: 99 },
        ] },
      { name: "Autobahn Black", tech: "Deep-Dye Film",
        tagline: "Affordable performance — the benefits of window film without breaking the bank.",
        warranty: "Lifetime warranty — no hidden fees or deductibles.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 43, ir: 13, uv: 99 },
          { sku: 15, vlt: 15, tser: 42, ir: 13, uv: 99 },
          { sku: 20, vlt: 19, tser: 39, ir: 13, uv: 99 },
          { sku: 30, vlt: 31, tser: 36, ir: 13, uv: 99 },
          { sku: 36, vlt: 36, tser: 35, ir: 13, uv: 99 },
          { sku: 40, vlt: 42, tser: 34, ir: 13, uv: 99 },
          { sku: 50, vlt: 49, tser: 30, ir: 13, uv: 99 },
          { sku: 56, vlt: 56, tser: 29, ir: 13, uv: 99 },
        ] },
    ],
  },

  // ── EDGE — programedge.com: navy-on-white quiet luxury, square uppercase CTAs
  edge: {
    name: "Edge",
    logoImg: "assets/edge-logo.png",
    pageTitle: "Tint. PPF. Coatings.",
    fontLinks: ["https://fonts.googleapis.com/css2?family=Gothic+A1:wght@500;600;700&family=Cormorant+Garamond:wght@600&display=swap"],
    theme: {
      "--accent": "#000035", "--accent-text": "#ffffff",
      "--header-bg": "#ffffff", "--header-text": "#394451", "--logo-color": "#000035",
      "--page-bg": "#f9f9f9", "--panel-bg": "#ffffff", "--panel-text": "#333333",
      "--muted": "#666666", "--line": "#e4e4e4",
      "--heading-font": "'Gothic A1',Arial,sans-serif", "--body-font": "Arial,Helvetica,sans-serif",
      "--radius": "4px", "--chip-radius": "0px", "--btn-radius": "0px", "--nav-transform": "uppercase",
      "--stage-day": "radial-gradient(ellipse 120% 90% at 50% 18%, #0d2b52 0%, #051531 55%, #010714 100%)",
      "--stage-night": "radial-gradient(ellipse 120% 90% at 50% 18%, #071d3a 0%, #030e22 55%, #01050e 100%)",
      "--hero-bg": "#000021", "--hero-text": "#ffffff", "--hero-sub": "#b7bfcd", "--eyebrow": "#9db1d6",
      "--card-border": "#e7e7e7",
    },
    hero: {
      eyebrow: "Edge Film Technologies",
      title: "Engineered to Elevate",
      sub: "Preview Edge window film on your vehicle — artistry, comfort, and protection, backed by hassle-free warranties.",
    },
    defaultPaint: "#1a1c1f",
    defaultShade: { seriesIdx: 0, vlt: 20, sku: 20 },
    // the brand site's own dealer-locator page (hosts the iframed z-tark locator)
    dealerUrl: "https://programedge.com/dealer-locator/", dealerCta: "Find a Dealer Near You",
    ctaTagline: "Find an Edge dealer near you to request a quote.",
    products: [
      { name: "Ceramic XR", tech: "Ceramic · 78% IRR",
        tagline: "The ultimate in performance and aesthetics — cutting-edge technology with sleek style.",
        warranty: "Limited lifetime warranty · 99% UV rejection.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 69, ir: 78, uv: 99 },
          { sku: 15, vlt: 15, tser: 64, ir: 78, uv: 99 },
          { sku: 20, vlt: 20, tser: 64, ir: 78, uv: 99 },
          { sku: 32, vlt: 32, tser: 58, ir: 78, uv: 99 },
          { sku: 43, vlt: 43, tser: 55, ir: 78, uv: 99 },
        ] },
      { name: "Spectra HP", tech: "High Performance",
        tagline: "Where cutting-edge technology meets sleek design — performance you can feel every day.",
        warranty: "Limited lifetime warranty · 99% UV rejection.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 63, ir: 72, uv: 99 },
          { sku: 15, vlt: 15, tser: 53, ir: 56, uv: 99 },
          { sku: 35, vlt: 35, tser: 43, ir: 46, uv: 99 },
          { sku: 45, vlt: 45, tser: 44, ir: 42, uv: 99 },
        ] },
      { name: "Carbon Crystalline", tech: "Carbon · Non-Metallic",
        tagline: "Stand out from the crowd — engineered to turn heads on every drive.",
        warranty: "Limited lifetime warranty · 99% UV rejection.",
        shades: [
          { sku: 5,  vlt: 5,  tser: 44, ir: 12, uv: 99 },
          { sku: 14, vlt: 14, tser: 42, ir: 12, uv: 99 },
          { sku: 20, vlt: 20, tser: 40, ir: 12, uv: 99 },
          { sku: 30, vlt: 30, tser: 38, ir: 12, uv: 99 },
          { sku: 35, vlt: 35, tser: 36, ir: 12, uv: 99 },
          { sku: 43, vlt: 43, tser: 34, ir: 12, uv: 99 },
          { sku: 50, vlt: 50, tser: 31, ir: 12, uv: 99 },
          { sku: 55, vlt: 55, tser: 29, ir: 12, uv: 99 },
        ] },
      { name: "Clear Comfort", tech: "Near-Clear · up to 93% IRR",
        tagline: "Comfort meets clarity — heat rejection with a nearly invisible finish.",
        warranty: "Limited lifetime warranty · 99% UV rejection.",
        shades: [
          { sku: 60, vlt: 60, tser: 56, ir: 93, uv: 99 },
          { sku: 70, vlt: 70, tser: 50, ir: 89, uv: 99 },
          { sku: 80, vlt: 80, tser: 44, ir: 68, uv: 99 },
        ] },
    ],
  },
};
